---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-bulk-manager

resources:
  - namespace.yaml
  - secrets.yaml
  - tls-secret.yaml
  - redis.yaml
  - app.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: gitlab-bulk-manager
