---
# TLS Secret - Copied from cert-manager namespace via Reflector
# Prerequisites:
#   - Reflector installed: https://github.com/emberstack/kubernetes-reflector
#   - Source secret exists in cert-manager namespace
#
apiVersion: v1
kind: Secret
metadata:
  name: wildcard.heeho.net
  namespace: gitlab-bulk-manager
  annotations:
    # Reflector annotation to copy from source
    reflector.v1.k8s.emberstack.com/reflects: "cert-manager/wildcard.heeho.net"
type: kubernetes.io/tls
data: {}
